### PR TITLE
Add operation name

### PR DESCRIPTION
**Pull request by fathiraz**

### CODE REVIEW

**Comment by fathiraz** [comment]
@smacker change query statement from this
Screen Shot 2020-03-14 at 10 08 59

to this
Screen Shot 2020-03-14 at 10 08 19


and, db type based on gorm dialect name.

**Comment by smacker** [comment]
Hi @fathiraz!

Thank you for the contribution but the change can expose sensitive information such as passwords, credit cards numbers and create security issues.

**Comment by fathiraz** [comment]
hai @smacker ! thankyou for great library..

i see... thankyou for the response..

anyway, i'd like to custom your script for my daily purpose just like this.. thats why, i want to use your code without your library.. do you mind?

**Comment by smacker** [comment]
no problem. You can just use `github.com/fathiraz/opentracing-gorm` instead of `github.com/smacker/opentracing-gorm` and implement any changes you need there.

**Pull request closed without merging**
